name: stellar_asset_lists
description: The Sellar Asset Lists package is designed to facilitate the integration of curated Stellar asset lists into Stellar applications and services. This package adheres to the Stellar Ecosystem Proposal (SEP-42) standard, providing a standardized mechanism for defining, validating, and sharing lists of Stellar assets. This helps to enhance user experiences and trust by ensuring consistency and ease of integration across the Stellar network.
version: 1.0.1
repository: https://github.com/godilite/stellar_asset_lists

environment:
  sdk: ^3.3.4

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
